---
title: "Graphs distances"
author: "Narbona Sabaté L."
output: html_notebook
---


  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install and load the following packages:
  
```{r, message=FALSE, warning=FALSE}
library(ggplot2)
```

#1. What is the distribution of call-distances?
```{r}
xdata <- read.delim('dataset_pred_prez_50-calls_chgd.txt')

seqID <- c(3,4,7,8,11,13,14,15,17,18,21,22,23,24,27,28,31,32,33,34,36,37,40,41,42,43,44,45,46,47,48,52)

bigrammes <- c()
lengths <- c()
for (id in seqID) {
  data <- xdata[xdata$Seq1 == as.character(id),]
  print(data)
  {for (i in 1:49){
    type1 <- data[data$Nb_call == i, "Type_call"]
    type2 <- data[data$Nb_call == i + 1, "Type_call"]
    bigramme <- paste(type1, type2, sep="")
    bigrammes <- c(bigrammes, bigramme)
    
    end <- data[data$Nb_call == i, "End_call"]
    begin <- data[data$Nb_call == i + 1, "Begin_call"]
    distance <- begin - end
    lengths <- c(lengths, distance)
  }
  }
}

distances_df <- data.frame(bigrammes, lengths)

```

#1. What is the distribution of call-distances?
```{r}
max <- which.max(density(distances_df$lengths)$y)
peak <- density(distances_df$lengths)$x[max]

ggplot(data=distances_df, aes(distances_df$lengths)) + 
  geom_histogram(aes(y =..density..), 
                 breaks=seq(0, 80, by = 0.01),
                 fill="blue",
                 alpha = 0.8) + 
  xlim(-1, 10) +
  geom_density(col=2, size = 1) + 
  geom_vline(xintercept = peak, size=1)+
  labs(title="Call-distance distribution (all sequences)", x="Distances", y="Count")
```